apiVersion: v1
kind: Namespace
metadata:
  labels:
  name: dns-test

---
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: dns-test
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: utils
      image: tutum/dnsutils
     #command: ["/bin/sh", "-ec", "while :; do dig www.google.com +tcp; sleep 10; done"]
      command: ["/bin/sh", "-ec", "while :; do dig www.google.com; sleep 10; done"]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
