apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: dns-test
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: utils
      image: tutum/dnsutils
      command: ["/bin/sh", "-ec", "while :; do dig www.google.com; sleep 10; done"]
      restartPolicy: Never
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
