apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: test-1
spec:
  containers:
  - name: hello-pod
    image: bmeng/hello-openshift
    ports:
    - containerPort: 8080
      hostPort: 9500

---
apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: test-2
spec:
  containers:
  - name: hello-pod
    image: bmeng/hello-openshift
    ports:
    - containerPort: 8080
      hostPort: 9500

