apiVersion: apps/v1
kind: Deployment
metadata:
  name: pwru-deployment
  namespace: default
  labels:
    app: pwru
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pwru
  template:
    metadata:
      labels:
        app: pwru
    spec:
      hostNetwork: true
      hostPID: true
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                - master
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
      - name: pwru
        image: ghcr.io/larsks/netutils:latest
        command: ['/bin/sh', '-c', 'sleep infinity']
        securityContext:
            privileged: true
            runAsUser: 0
            capabilities:
              add:
                - CAP_BPF
                - CAP_SYS_ADMIN
                - CAP_NET_ADMIN
                - CAP_NET_RAW
      volumeMounts:
        - mountPath: /sys/kernel/
          name: sys-kernel
        - mountPath: /lib/modules/
          name: lib-modules
        - mountPath: /host
          name: host
        - mountPath: /sys/kernel/debug/tracing   
          name: sys-kernel-debug
      terminationGracePeriodSeconds: 0
      nodeSelector:
        kubernetes.io/hostname: ch54j22-b5564-l2wjp-master-0
      volumes:
      - name: sys-kernel
        hostPath:
          path: /sys/kernel
          type: Directory
      - name: sys-kernel-debug
        hostPath:
          path: /sys/kernel/debug/tracing
          type: Directory
      - name: lib-modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: host
        hostPath:
          path: /
          type: Directory

---

