
---
apiVersion: v1
kind: Namespace
metadata:
 name: xlat-test

---
apiVersion: v1
kind: Pod
metadata:
 name: hello-pod
 namespace: xlat-test
 labels:
  app: hello-pod
spec:
 containers:
 - name: hello-world
   image: gcr.io/google-samples/node-hello:1.0
   ports:
   - containerPort: 8080
     protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
 name: hello-pod
 namespace: xlat-test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-pod
  type: ClusterIP


