apiVersion: v1
kind: Namespace
metadata:
 name: test-1
 labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    k8s.ovn.org/primary-user-defined-network: ""

---
apiVersion: v1
kind: Namespace
metadata:
 name: test-2
 labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    k8s.ovn.org/primary-user-defined-network: ""


