
---

kind: UserDefinedNetwork
apiVersion: k8s.ovn.org/v1
metadata:
  name: test-network
  namespace: test-1
spec:
  topology: Layer2
  layer2:
       role: Primary
       subnets: ["10.10.0.0/16"]

---

kind: UserDefinedNetwork
apiVersion: k8s.ovn.org/v1
metadata:
  name: test-network
  namespace: test-2
spec:
  topology: Layer2
  layer2:
       role: Primary
       subnets: ["10.10.0.0/16"]


