apiVersion: v1
kind: Pod
metadata:
  name: sctpserver
  labels:
    app: sctpserver
spec:
  containers:
    - name: sctpserver
      image: quay.io/openshifttest/centos-network@sha256:48da37205f9b43424e0983d4c5e7e07f77b7ba1504bbe35e2f264c75dcb4cd15
      ports:
        - containerPort: 30102
          name: sctpserver
          protocol: SCTP
  nodeSelector:
   kubernetes.io/hostname: ci-ln-6rzv9ik-72292-ctfxk-worker-b-n2x9r

---
apiVersion: v1
kind: Pod
metadata:
  name: sctpclient
  labels:
    app: sctpclient
spec:
  containers:
    - name: sctpclient
      image: quay.io/openshifttest/centos-network@sha256:48da37205f9b43424e0983d4c5e7e07f77b7ba1504bbe35e2f264c75dcb4cd15
  nodeSelector:
   kubernetes.io/hostname: ci-ln-6rzv9ik-72292-ctfxk-worker-c-ls2sf

